apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobless_backend
spec:
  project: default
  source:
    repoURL: https://github.com/arthurleroudier/Jobless_deployment.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: arthurleroudier-aleroudier
  syncPolicy:
    automated:
      selfHeal: true
